package io.github.bsautner.ksp.processor

object Const {

    val comment = """
         This code was generated by KSP annotation processor Kobold
         https://github.com/bsautner/kobold       
    """.trimIndent()

}