{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kobold-api/0.0.1/kobold-api-0.0.1.module",
    "group": "io.github.bsautner.kobold",
    "module": "kobold-api",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13-milestone-3"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-wasm-js-0.0.1.klib",
          "url": "kobold-api-0.0.1.klib",
          "size": 20847,
          "sha512": "55dd25512279b6d988bd6e1e3226c3e0ec2e2fac0926bf0488a138f80479d6ee668d7d02f69a0e1a6c08394a64680a30081addc0373d58e639fe74bb1c624d21",
          "sha256": "d2a2916d5b74993f8b41f88e61d6b76c64fda4a47524a6147410579076acd5d8",
          "sha1": "af72f47722c0b10a70c0daaa5b5471f0ee4d742b",
          "md5": "96de2fcc260259b3c94d45d621d615fa"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-wasm-js-0.0.1.klib",
          "url": "kobold-api-0.0.1.klib",
          "size": 20847,
          "sha512": "55dd25512279b6d988bd6e1e3226c3e0ec2e2fac0926bf0488a138f80479d6ee668d7d02f69a0e1a6c08394a64680a30081addc0373d58e639fe74bb1c624d21",
          "sha256": "d2a2916d5b74993f8b41f88e61d6b76c64fda4a47524a6147410579076acd5d8",
          "sha1": "af72f47722c0b10a70c0daaa5b5471f0ee4d742b",
          "md5": "96de2fcc260259b3c94d45d621d615fa"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "api-wasm-js-0.0.1-sources.jar",
          "url": "kobold-api-0.0.1-sources.jar",
          "size": 5305,
          "sha512": "d2f92edf3cd2a41f132be345a58ac4a65d25e4395cb12ce1dc758ed41356c19c9fe40f771d1cc3018089815db1f1ef7ebc732df0497e09f721f596907438a065",
          "sha256": "3e6427e5bb34c903985642e34cb27f41d94a30b9c972c1137b55cd58b59111b9",
          "sha1": "52fac52c103b333de3ece4e760bb6b5eb6c21434",
          "md5": "f4e7891c17073ec151ede0b13c32b034"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-0.0.1.kotlin_resources.zip",
          "url": "kobold-api-0.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 346,
          "sha512": "59bd05eb1709f9116be8e0eb13784078d5731a8d02cc3bdba96eebce6a6cb56e929522c5006e7b49efc0d42ce90a44cc45ae12c059357412c7e1a7f9c67f40cb",
          "sha256": "f07eea08cf0810271d9e5d49f08818bcf13d69c1aa9386cdad85a55bb674a69e",
          "sha1": "e41142bd347e1fc21f2f58879c55dbd0b402b211",
          "md5": "eabefd017357f2f13c4fff9389b23bfe"
        }
      ]
    }
  ]
}
