name: CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  pages: write

env:
  INSTANCE: 'Writerside/k'
  DOCKER_VERSION: '243.22562'

jobs:
  build:
    outputs:
      artifact: ${{ steps.define-ids.outputs.artifact }}
      algolia_artifact: ${{ steps.define-ids.outputs.algolia_artifact }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        id: define-ids
        run: |
          ./gradlew build dokkaGenerate
          # Process INSTANCE for naming
          INSTANCE=${INSTANCE#*/}
          INSTANCE_ID_UPPER=$(echo "$INSTANCE" | tr '[:lower:]' '[:upper:]')
          ARTIFACT="webHelp${INSTANCE_ID_UPPER}2-all.zip"
          ALGOLIA_ARTIFACT="algolia-indexes-${INSTANCE_ID_UPPER}.zip"
          
          echo "INSTANCE_ID_UPPER: $INSTANCE_ID_UPPER"
          echo "ARTIFACT: $ARTIFACT"
          echo "ALGOLIA_ARTIFACT: $ALGOLIA_ARTIFACT"
          
          echo "INSTANCE_ID_UPPER=$INSTANCE_ID_UPPER" >> $GITHUB_ENV
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
          echo "ALGOLIA_ARTIFACT=$ALGOLIA_ARTIFACT" >> $GITHUB_ENV
          echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT
          echo "algolia_artifact=$ALGOLIA_ARTIFACT" >> $GITHUB_OUTPUT

      - name: Copy Dokka HTML to Writerside
        run: |
          mkdir -p Writerside/api-docs
          if [ -d "api/build/dokka/html" ]; then
            cp -rv api/build/dokka/html/* Writerside/api-docs/
          else
            echo "Dokka output directory not found!"
            exit 1
          fi

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          docker-version: ${{ env.DOCKER_VERSION }}

      # Upload the contents of the Writerside folder (not the folder itself)
      - name: Upload Writerside docs
        uses: actions/upload-artifact@v4
        with:
          name: writerside
          path: Writerside/.   # Notice the dot (.) to include the folder's contents

      - name: Save additional build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ steps.define-ids.outputs.artifact }}
            artifacts/report.json
            artifacts/${{ steps.define-ids.outputs.algolia_artifact }}
          retention-days: 7

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download additional build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      # Download the writerside artifact into a folder named "pages"
      - name: Download Writerside docs artifact
        uses: actions/download-artifact@v4
        with:
          name: writerside
          path: pages
          
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages   # This folder now contains your site's root content

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
