name: Sign and Publish

on:
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      
      - name: Build Project
        env: 
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}     
        run: |
          ./gradlew clean build publish -Pversion=${{ github.event.release.tag_name }}
          ./gradlew :api:zipPublishedArtifacts
          ./gradlew :ksp:zipPublishedArtifacts
  

      - name: Upload Bundle to Maven Central
        env:
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
        run: |
          
          curl --request POST \
            --verbose \
            --header "Authorization: Bearer $SONATYPE_TOKEN" \
            --form bundle=@./api/build/zips/api.zip \
            https://central.sonatype.com/api/v1/publisher/upload
          
           curl --request POST \
            --verbose \
            --header "Authorization: Bearer $SONATYPE_TOKEN" \
            --form bundle=@./ksp/build/zips/ksp.zip \
            https://central.sonatype.com/api/v1/publisher/upload


        
