name: Sign and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      
      - name: Build Project
        env: 
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}     
        run: |
          ./gradlew clean build :api:zipPublishedArtifacts
          ls -la ./api/build/repo/io
          zip -r ./api/build/repo/io ./api/build/api-bundle.zip
          ls -l ./api/build/api-bundle.zip
          

      - name: Upload Bundle to Maven Central
        env:
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
        run: |
          cd ./api/build
          curl --request POST \
            --verbose \
            --header "Authorization: Bearer $SONATYPE_TOKEN" \
            --form bundle=@api-bundle.zip \
            https://central.sonatype.com/api/v1/publisher/upload


        
