name: Sign and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      
      - name: Build Project
        env: 
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}     
        run: ./gradlew clean build

      - name: Bundle Artifacts into Zip
        run: |
          mkdir -p deployment
          # Copy the files from the API module build output.
          cp -v api/build/libs/* deployment/
          # Change into the deployment folder and zip everything.
          cd deployment
          zip -r ../central-bundle.zip .
          cd ..
          ls -l central-bundle.zip


        
